---

  - name: PLAYBOOK PARA OBTER PODS EM EXECUÇÃO
    # --------------------------------------------------
    block:
    # --------------------------------------------------
  
      - name: OBTER PODS EM EXECUÇÃO
        k8s_info:
          kind: Pod
          namespace: "{{ namespace }}"
          label_selectors:
            - "app = {{ name }}"
        register: pods

      - debug:
          var: "{{ pods }}"

      # - set_fact:
      #     pods_count: "{{ pods.resources | count }}"

      # - debug:
      #     var: "{{ pods_count }}"
  
      - set_fact:
          add_info: "Obtenção de pods em execução executada com SUCESSO!!!"
  
      - debug:
          msg: "{{ add_info }}"
  
  
    # --------------------------------------------------
    rescue:
    # --------------------------------------------------
      - name: SET FACT MSG RESULT FAILED
        set_fact:
          msg_result: "Obtenção de pods em execução executada com ERRO!!!"
  
      - debug:
          var: msg_result
  
      - fail:
          msg: "{{ msg_result }}"
  