---

- name: OBTER QUANTIDADE DE RÉPLICAS
  # --------------------------------------------------
  block:
  # --------------------------------------------------

    - name: EM EXECUÇÃO
      k8s_info:
        name: "{{ name }}"
        kind: Deployment
        namespace: "{{ namespace }}"
      register: result_execucao

    - debug:
        var: "{{ result_execucao }}"

    - set_fact:
        ready_replicas_count: "{{ result_execucao.resources[0].status.readyReplicas }}"

    - set_fact:
        add_info: "Obtenção de réplicas em execução executada com SUCESSO!!!"

    - debug:
        msg: "{{ add_info }}"


  # --------------------------------------------------
  rescue:
  # --------------------------------------------------
    - name: SET FACT MSG RESULT FAILED
      set_fact:
        msg_result: "Obtenção de réplicas executada com ERRO!!!"

    - debug:
        var: msg_result

    - fail:
        msg: "{{ msg_result }}"
  