---

- name: ALTERAR QUANTIDADE DE RÉPLICAS EM EXECUÇÃO
  # --------------------------------------------------
  block:
  # --------------------------------------------------

    - k8s_scale:
        name: "{{ name }}"
        api_version: v1
        kind: Deployment
        namespace: "{{ namespace }}"
        replicas: "{{ quantity }}"
      register: result

    - set_fact:
        pods_in_running: result.spec.replicas

    - debug:
        var: "{{ pods_in_running }}"

    - set_fact:
        add_info: "Alteração da quantidade de réplicas executada com SUCESSO!!!"

    - debug:
        msg: "{{ add_info }}"


  # --------------------------------------------------
  rescue:
  # --------------------------------------------------
    - name: SET FACT MSG RESULT FAILED
      set_fact:
        msg_result: "Alteração da quantidade de réplicas executada com ERRO!!!"

    - debug:
        var: msg_result

    - fail:
        msg: "{{ msg_result }}"
